[nginx-rate-limit]
enabled  = true
filter   = nginx-rate-limit
logpath  = /var/log/nginx/access.log
# If IP triggers 5 x 429 within 20 seconds → ban for 60 seconds
maxretry = 5
findtime = 20
bantime  = 60
